["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "./lib"

["protostar.contracts"]
main = [
    "./src/main.cairo",
]


["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]